### ISSUE TITLE
Add image section [pictures / images / photos]

### ISSUE THREAD

**Issue by roboyoshi** [roboyoshi/datacurator-filetree#25]
I want to set the main folder for everything image/picture/photo related.

I personally thing the broadest term is "images".. pretty much covers everything.. but as pointed out elsewhere, it's a term also used for non-picture related stuff (like the image of a company in the public view).

TODO:
Settle the base-folder and create sub-folders accordingly..

Current Understanding and use:

* images = perception of sth (e.g. The image of myself in a mirror)
* pictures = comes from "pictura" meaning "painted".. so it's rather attached to everything artificially created like drawings, paintings, oil on canvas, etc.
* photo = fairly new word that has been coined by the camera evolution and is hardly attached to everything that has been taken by a camera.

```
/images/
    pictures/ # art drawings and paintings organized by year/artist/genre/style ??
    photos/ # image taken by photographers/people/etc with an analog/digital camera
    ??
```

References:
* https://ell.stackexchange.com/questions/10786/photo-vs-picture-vs-image-what-is-the-difference-between-them#63423
* https://www.quora.com/Whats-the-difference-between-a-picture-image-and-photo

**Comment by roboyoshi** [comment]
From #18 :

```
TODO:
Specify a reasonable default for personal images
Base on Adobe Lightroom Template
Check for reddit posts on this (I vaguely remember the Timestamp discussion on the subreddit)
```

**Comment by Thunkstation** [comment]
My pull request, #35, should help with this.
