### ISSUE TITLE
Add dataset section for leaks (wikileaks, jfk files etc.)

### ISSUE THREAD

**Issue by SebRut** [roboyoshi/datacurator-filetree#26]

**Comment by roboyoshi** [comment]
Good point, will probably check the-eye and other sources to find a good base directory. for now I'd consider them dumps of the www (so `/root/web/`)

**Comment by roboyoshi** [comment]
Another update here:
Other datasets like: DB Dumps / CSV Files, Image Collection (CIFAR-10/CIFAR-100) are probably also included here. Its one of the few I'd consider worthy of another top-level folder..

**Comment by roboyoshi** [comment]
Not sure why I never closed this, but news (incl. leaks) as well as datasets now go into `root/archives`.
