### ISSUE TITLE
Change audio section

### ISSUE THREAD

**Issue by roboyoshi** [roboyoshi/datacurator-filetree#27]
TODO:
- Consider renaming 'artists' to 'music' and merge with 'compilations'
- Gather Community Feedback
  - Ask [r/musichoarder](https://www.reddit.com/r/musichoarder/) for folder structures used in the wild
  - Check Hydrogenaud.io as well.
  - And Discord!
- Add more folders
  - soundfx
  - recordings (voice memos)
  - ..?

The most common approach I've seen is just `music/$artist/$album/track`
Since we also need to fit other kinds of audio (e.g effects, podcasts, etc.) into the same section it makes a lot more sense to flatten music and put everything into one directory.

The artists/books/soundtracks is a rather personalized version and can be added as an "alternative" structure.

**Comment by gravelld** [comment]
At the moment I agree with merging these into one folder, unless the rules for some of the defined folders like `Compilations` is changed.

The main reason is that I find the distinction arbitrary. As an example, under the current tree, 'what about' one-artist compilations?
