### ISSUE TITLE
Add subfolders for source types under soundtracks

### ISSUE THREAD

**Issue by fionera** [roboyoshi/datacurator-filetree#33]
I think it would be better to have Subfolders for Movies, Games etc for Soundtracks since it will be full

**Comment by roboyoshi** [comment]
Yes, that's what I do as well, but not sure if it works for everyone.

TODO:
- [ ] Add subfolders to `root/audio/soundtracks/`:

```
movie
tv-series
tv-anime
tv-cartoon
videogame
```

**Comment by roboyoshi** [comment]
done.
