### ISSUE TITLE
Adult Section Missing Parts

### ISSUE THREAD

**Issue by roboyoshi** [roboyoshi/datacurator-filetree#42]
TODO:
- [x] Missing in root readme
- [x] Missing interactive section in adult readme

**Comment by Lilja** [comment]
Also, an `interactive` folder is missing in the file tree.

**Comment by roboyoshi** [comment]
Yeah I noticed that too, will edit this bug to include this.

**Comment by roboyoshi** [comment]
Fixed. `interactive` had been renamed to `games` a while a go to keep things simple. So it was already included.
