### ISSUE TITLE
Proposal: a 'clips' folder within the video folder for YouTube/Reddit/Twitter/etc. clips

### ISSUE THREAD

**Issue by HALL-MiGHT** [roboyoshi/datacurator-filetree#47]
I have downloaded multiple videos that intrigued me and I wanted to keep around but didn't fall into some other category. I have personally created one but I think it would be useful.

**Comment by roboyoshi** [comment]
I personally put them into `root/videos/web`, but `clips` is also a nice proposal. With YouTube and reddit also havin 40+ minute videos for let's plays and documentations/essays/broadcasts a `clip` might be too short. I'll have to research a bit more in what broader category all this falls.

**Comment by roboyoshi** [comment]
Closing Notes: I went with the 'web' directory, since I've been using that successfully for quite some time now without bothering me too much.
