### ISSUE TITLE
Where should I put demeter output?

### ISSUE THREAD

**Issue by Wingysam** [roboyoshi/datacurator-filetree#48]
Currently, I have it as /Books, but maybe it should be /Literature/demeter?

**Comment by rwenz3l** [comment]
@Wingysam I'm not sure what you mean with `Demeter`. It usually refers to a greek godess, but I think you mean something different.
See https://en.wikipedia.org/wiki/Demeter_(disambiguation) and please clarify that for me.

**Comment by roboyoshi** [comment]
@Wingysam I'm not sure what you mean with Demeter. It usually refers to a greek godess, but I think you mean something different.
See https://en.wikipedia.org/wiki/Demeter_(disambiguation) and please clarify that for me.

**Comment by Wingysam** [comment]
Oops, I forgot to mention that. https://github.com/gnur/demeter

**Comment by roboyoshi** [comment]
@Wingysam ok, well 2 Options come to mind:
- `archives/internet` if you want to preserve it "as-is" 
- `literature/` if you want to "dump it". I think most people do not have a "fully sorted" structure here, so feel free to just mass-download it into this.
