### ISSUE TITLE
Files related to your current/previous job 

### ISSUE THREAD

**Issue by atomtm** [roboyoshi/datacurator-filetree#49]
Where would you put files that are specific to your current job (or maybe previous or side project you re working on ) that you access daily and are of different types , i.e. diagrams , datasheets , etc ? 
If there should be a special folder , on what hierarchy level would you place it ?

**Comment by roboyoshi** [comment]
@atomtm - I usually have a seperate filetree for this kind of stuff. Do not focus on solving everything within 1 filetree. I'd need to begin with the very very root of everything to cover that.
The current implementation here is more aimed at the hoarders and all the content they acquire.

For Personal Stuff, I tend to create a folder structure like this, where root is my home directory:

```
root/
  Sync/
    Drive/
      notes/
      diagrams/
      images/
  Projects/
    ###-PROJECT/
  Repositories/
    private/
      datacurator-filetree/
```

I then create backups of e.g. `Projects` in the `archives/backups/projects` folder (https://github.com/roboyoshi/datacurator-filetree/tree/master/root/archives)

In general, I put personal documents somewhere else, so I can sync it properly across devices.
Projects need to be on external disks often (Editors/Musicians/Writers/etc.), so I'd expect there to be a whole new "root". I think I need to create a separate branch for that :)

**Comment by roboyoshi** [comment]
I quickly added my Home-Tree (Base). Maybe that helps.
https://github.com/roboyoshi/datacurator-filetree/tree/user/roboyoshi.home/root

**Comment by atomtm** [comment]
> I think I need to create a separate branch for that :)
Please do! <3

**Comment by roboyoshi** [comment]
I added the branch and also included a Link to other branches on the main readme. Hope that helps.
