### ISSUE TITLE
Proposal: Add a folder tree view image to the README

### ISSUE THREAD

**Issue by Teraskull** [roboyoshi/datacurator-filetree#51]
It will help visualize this whole file tree, without needing to go through all folders to see what is inside.

**Comment by roboyoshi** [comment]
Indeed a good idea, I will add this.

**Comment by roboyoshi** [comment]
@Teraskull done!

**Comment by Teraskull** [comment]
> @Teraskull done!

Wow, that was fast, nice!

**Comment by roboyoshi** [comment]
That was basically a no-brainer change. Most of the other issues here require a lot of research and me testing several patterns on stuff that I haven't touched in my life :D
