### ISSUE TITLE
Add Installers Folder In Software

### ISSUE THREAD

**Issue by Senko-Dev** [roboyoshi/datacurator-filetree#54]
Everyone Will Need To Keep Installers For Fonts, Plugins And Apps. Can We Add A Folder For This
[System.zip](https://github.com/roboyoshi/datacurator-filetree/files/4434661/System.zip)

**Comment by diligamer** [comment]
Name system.zip "Installers" After Extraction

**Comment by diligamer** [comment]
@roboyoshi

**Comment by Teraskull** [comment]
> Name system.zip "Installers" After Extraction

I have it this way:

\root\software\Applications\windows\Packages
\root\software\Fonts

**Comment by diligamer** [comment]
> > Name system.zip "Installers" After Extraction
> 
> I have it this way:
> 
> \root\software\Applications\windows\Packages
> \root\software\Fonts

Having Your Installers And Software Library For VMs Mixed Is Bad.

**Comment by roboyoshi** [comment]
Not really sure yet what to do with this one. My software library is not that big to cover everything yet and I'm still not sure what the desired state for OP is. Maybe @diligamer can elaborate a bit more what needs to be stored here and how it makes more sense.

**Comment by diligamer** [comment]
Apps, Fonts And Plugins

**Comment by diligamer** [comment]
@roboyoshi

**Comment by roboyoshi** [comment]
I have added Fonts Today, Applications have always been there. If there is a "Installer" for Something, I would recommend putting them in either of these. PlugIns... I'm not sure. Add it as you see fit, I don't see how they fit into this complex structure yet, without a big pile of plugins to look through.

**Comment by Senko-Dev** [comment]
Ok
