### ISSUE TITLE
Possible redundancy

### ISSUE THREAD

**Issue by FlameHorizon** [roboyoshi/datacurator-filetree#55]
**Observation**
Location _datacurator-filetree/root/images/photos/_ contains directories like _personal-photos_ or _other-photos_. 

Word _photos_ in _*-photos_ seems to be redundant, because information about the context is already contained in the parent directory.

**Change proposition**
Remove word _photos_ from every directory in the _datacurator-filetree/root/images/photos/_

**Comment by rwenz3l** [comment]
Good observation! I will change this.
