### ISSUE TITLE
Where should Webcomics go?

### ISSUE THREAD

**Issue by davralin** [roboyoshi/datacurator-filetree#63]
I see your comment under `literature`, but I'm not sure if I agree with you for webcomics.

Would something like [this](https://www.gocomics.com/calvinandhobbes/) be considered literature? Or is it an image? Webpage?

**Comment by iopemo** [comment]
Hopefully this might clear it up 

[Comics aren't like plays, novels, or essays. Those things are real literature.” Comics are usually comprised of art, with or without text, arranged in sequence. As such, they are different from plays, novels, or essays.](https://www.comicsineducation.com/home/comics-arent-real-literature-and-other-stupid-things-people-say#:~:text=%E2%80%9CComics%20aren't%20like%20plays,plays%2C%20novels%2C%20or%20essays.)

**Comment by davralin** [comment]
This isn't saying comics isn't literature - this is arguing wether webcomics is a webpage, an image, or if it's indeed comics.

I think it's hard to make the case that XKCD is in the same genre as "Spiderman"-comicbooks.
