### ISSUE TITLE
root file name suggestion :enhancement

### ISSUE THREAD

**Issue by gChingon** [roboyoshi/datacurator-filetree#66]
# Root file *re*name suggestion

personally I use something similar, though the root filenames are:

`done/aprende,comix,dimaj,libros,movie,pr0n,rom,shows,yuzik` `frag/aprende,comix,dimaj,libros,movie,pr0n,rom,shows,yuzik`

the main purpose for the naming structure is to be able to "jump" into a directory by typing the first letter then `tab` there are no duplicate letters per directory. 

if this filetree is used, the only issue I see running into is trying to get into an `A` directory as there are 3 `A` named folders `Adult, Archive, Audio` 

Granted this is only an "issue" if you "live" in Command-Line. I personally use spanish and turkish words where I had an issue with directories beginning with the same letter.

`Porn/Pr0n/P0rn` can replace `Adult` though it has more negative connotations or remain as `Adult` and change one of the others

`Backup/Records/Cold(storage)` > `Archive` I use `Backup` nearly every Latin letter based language has `Arc/Ark` in the translation. Turkish is usually a good choice to not run into this issue.

`Sound/Sonic/Phonic` > `Audio` 

To be clear this is a very good filetree, This isn't an issue as much as a preference.  And this gave me an idea as to condensing my own filetree

**Comment by roboyoshi** [comment]
Well sounds like you found good use here!

I do take great care in choosing the right words for the main sections. It's debatable, absolutely.
You make a great point: translations. Never thought about that.

I also live a lot in the cli and switching between 'archive' and 'audio' ist just `ar<Tab>` or `au<Tab`. So I don't think that's a big problem.

I don't think there is much enhancement from this issue, but I'll keep your points in mind while working on it.
