### ISSUE TITLE
Please redirect Q&A + Ideas => GitHub Discussions.

### ISSUE THREAD

**Issue by roboyoshi** [roboyoshi/datacurator-filetree#69]
You can now ask questions and discuss ideas [in the GitHub Discussions tab](https://github.com/roboyoshi/datacurator-filetree/discussions).

**Comment by roboyoshi** [comment]
Discussions have not been proven useful so I removed this. New Ideas and problems are best managed in the simple form of issues here.

**Comment by Nyral** [comment]
@roboyoshi Thank you for making this project, it has been very useful.
