### ISSUE TITLE
consider renaming "interactive" section

### ISSUE THREAD

**Issue by roboyoshi** [roboyoshi/datacurator-filetree#9]
- interactive/videogames and software/videogames are both possible and valid
- it is not clear to the average user what "interactive" means/contains.

**Comment by joelra** [comment]
What about just "games"? It seems that interactive is pointing to some form of a game, digital or not.  Sub folders could be "cardgames", "boardgames", "videogames", each then having their own folder for the particular game.

**Comment by roboyoshi** [comment]
@joelra a good start and most certainly more acessible to the common user. It was also one of my top alternatives. Although I fear that thise leaves not a lot of room for other interactive contents, but  I can't really think of any.

The problem is probably more that videogames are basically software, yet software got it's own section. Not having `games/videogames`, but `software/videogames` is confusing.

If one really wants to sort this right, then my take would be:
Have actual games,updates,metadata stored like this:
`games/videogames/<console>/Game Title (Year)/foo/bar.ext`
and Videogame Software (Like Homebrew, OS copies, BIOS, etc.) like this:
`software/<console>/{bios,homebrew,apps,...}/foo/bar.ext`

The interactive section can be used as an alternative but in the end it's probably better to rank it as No.2 and make `games` the default.

Thanks a lot for the input, I'll make a change accordingly.
